pipeline {

    agent any

    tools {
        maven 'mymaven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'Practice-lab-excercises',
                    url: 'https://github.com/DevopsAkhila/Devops-Files.git'
            }
        }

        stage('Compile Main Code') {
            steps {
                // Compile Java source code using custom pom.xml location
                sh 'mvn -f "Lab excercise-3/pom.xml" clean compile'
            }
        }

        stage('PMD Analysis') {
            steps {
                // Run PMD static code analysis
                sh 'mvn -f "Lab excercise-3/pom.xml" pmd:pmd'
            }

            post {
                always {
                    // Publish PMD report using Warnings Next Generation plugin
                    // enabledForFailure=true ensures report is published even if build fails
                    recordIssues(
                        enabledForFailure: true,
                        tools: [pmdParser(pattern: '**/pmd.xml')]
                    )
                }
            }
        }

        stage('Test Code') {
            steps {
                // Run unit test cases (JUnit)
                sh 'mvn -f "Lab excercise-3/pom.xml" test'
            }
        }
    }
}
