#Running on a single agent

pipeline {
    agent { label 'staticagent_linuxnode' }
    tools { maven 'mymaven' }

    stages {
        stage('Clean Workspace') {
            steps { deleteDir() }
        }

        stage('Clone the repo') {
            steps {
                git branch: 'java-app',
                    url: 'https://github.com/DevopsAkhila/Devops-Files.git'
                echo "Cloned the repository successfully"
            }
        }

        stage('Build the project') {
            steps {
                    sh 'mvn clean package'
                }
            }

        stage('Test the project') {
            steps {
                    sh 'mvn test'
                }
            }

        stage('Deploy the project') {
            steps { echo "Deploying the project..." }
            post {
                success {
                    echo "Deployment successful!"
                    junit 'target/surefire-reports/*.xml'
                        archiveArtifacts artifacts: 'target/*.jar'
                        slackSend(channel: '#all-slack-demo', message: "Deployment successful and Artifact archived!")
                }
                    
                failure {
                    echo "Deployment failed."
                  
                        archiveArtifacts artifacts: 'target/*.jar'
                         slackSend(channel: '#all-slack-demo', message: 'Deployment failed. Artifact still archived')
                    }
                   
                }
            }
        }
    }
